server:
  port:
    8082
spring:
  application:
    name: audit-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/audit_db
    password: Root@123




  jpa:
    hibernate:
      ddl-auto: update
      generate-ddl: true
      show-sql: true
    properties:

      dialect: org.hibernate.dialect.MySQL57Dialect

      format_sql: true
logging:
  level.org.springframework: debug

